#!/bin/bash

export MIRANDMORE_HOME=$(dirname $(readlink -f $0))
export PYTHONPATH=$PYTHONPATH:$MIRANDMORE_HOME/lib
export PATH=$MIRANDMORE_HOME/bin:$PATH
export SCONS_HORRIBLE_REGRESSION_TEST_HACK=1
export TOOL_DIR=$MIRANDMORE_HOME/tools
export R_LIBS=$TOOLS_DIR/R_libs
export SCONS_VER='3.1.2'

mkdir -p $TOOL_DIR ;
mkdir -p $MIRANDMORE_HOME/bin

## check whether Scons is installed and install it if not
command -v scons >/dev/null 2>&1 ||\
{ echo >&2 "I require Scons but it's not installed. Installing Scons..."; 
wget -N -c http://prdownloads.sourceforge.net/scons/scons-local-$SCONS_VER.tar.gz -O $TOOL_DIR/scons-local-$SCONS_VER.tar.gz ;

mkdir -p $TOOL_DIR/scons ; 

tar -xf $TOOL_DIR/scons-local-$SCONS_VER.tar.gz -C $TOOL_DIR/scons ; 

ln -s $TOOL_DIR/scons/scons.py $MIRANDMORE_HOME/bin/scons ; }

cd $MIRANDMORE_HOME/bin
ln -s ../src/utils/* .
cd -

scons -f $MIRANDMORE_HOME/src/sconstructs/install.py $1
