#!/bin/bash

export MIRANDMORE_HOME=$(dirname $(readlink -f $0))
export PYTHONPATH=$PYTHONPATH:$MIRANDMORE_HOME/lib
export PATH=$MIRANDMORE_HOME/bin:$PATH
export R_LIBS="$MIRANDMORE_HOME/packs/R_libs"
export SCONS_HORRIBLE_REGRESSION_TEST_HACK=1
export TOOL_DIR=$MIRANDMORE_HOME/tools

mkdir -p $TOOL_DIR ;

## check whether Scons is installed and install it if not
command -v scons >/dev/null 2>&1 ||\
{ echo >&2 "I require Scons but it's not installed. Installing Scons..."; 
wget -N -c http://prdownloads.sourceforge.net/scons/scons-local-2.5.1.tar.gz -O packs/scons-local-2.5.1.tar.gz ;

mkdir -p $TOOL_DIR/scons ; 

tar -xf $TOOL_DIR/scons-local-2.5.1.tar.gz -C $TOOL_DIR/scons ; 

ln -s $TOOL_DIR/scons/scons.py $MIRANDMORE_HOME/bin/scons ; }

cd $MIRANDMORE_HOME/bin
ln -s ../src/utils/* .
cd -

scons -f $MIRANDMORE_HOME/src/sconstructs/install.py $1
