#!/bin/bash
PYTHON_VERSION=`python --version | sed -r "s/Python ([0-9]\.[0-9]).*/\1/"`
export MIRANDMORE_HOME=$(dirname $(readlink -f $0))
export PYTHONPATH=$MIRANDMORE_HOME/lib:$MIRANDMORE_HOME/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH
export PATH=$MIRANDMORE_HOME/bin:$PATH
#export R_LIBS="$MIRANDMORE_HOME/tools/R_libs"
scons -f $MIRANDMORE_HOME/src/sconstructs/main.py $1
